[build-system]
requires = ["setuptools>=61", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytdx"
dynamic = ["version"]
description = "A Python Interface to TDX protocol"
requires-python = ">=3.8"
authors = [
    {name = "RainX", email = "i@rainx.cc"},
    {name = "yutiansut"},
    {name = "mai1346"},
]
dependencies = [
    "click",
    "pandas",
    "cryptography",
]

[project.scripts]
hqget = "pytdx.bin.hqget:main"
hqreader = "pytdx.bin.hqreader:main"
get_tts = "pytdx.bin.get_tdx_trader_server:main"
hqbenchmark = "pytdx.bin.hqbenchmark:main"

[tool.setuptools.packages.find]
include = ["pytdx*"]

[tool.setuptools_scm]
version_scheme = "only-version"
local_scheme = "no-local-version"
